name = "shpe-uwm"
main = ".open-next/worker.js"
compatibility_date = "2025-10-16"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "shpe-uwm"
