main = ".open-next/worker.js"
name = "shpe-uwm"
compatibility_date = "2025-10-20"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

pages_build_output_dir = ".open-next/cloudflare"
