name = "shpe-uwm"
main = ".open-next/worker.js"
compatibility_date = "2025-10-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "shpe-uwm"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
CLOUDFLARE_ACCOUNT_ID = 74c637f0698bc402f3c4dda4bd83a0ad
CLOUDFLARE_API_TOKEN = JPqqYiGzZYS0L748acaQDmBBpLFRt0CizF09_fPU
