import type { EventItem } from "@/components/event-card";

export const events: EventItem[] = [
    {
        id: "gbm-1",
        title: "First General Body Meeting",
        start: "2025-09-17T16:00:00",
        end: "2025-09-17T19:00:00",
        location: "UWM LECWC 203",
        description: "Tomorrow, we have our first general body meeting, it's a more lowkey event just to get to know people in the chapter and see what events we have planning this year.",
        category: "Workshop",
    },
    {
        id: "ceas-involvement-fair",
        title: "CEAS Involvement Fair",
        start: "2025-09-18T11:30:00",
        end: "2025-09-18T13:00:00",
        location: "UWM EMS building",
        description: "Come and see us at the CEAS involvement fair to get to know other STEM orgs on campus. If you went to the Involvement fair last week, it's going to pretty much the same thing except STEM related.",
        category: "Outreach",
    },
    {
        id: "speed-dating",
        title: "Speed Dating",
        start: "2025-09-18T17:30:00",
        end: "2025-09-18T18:30:00",
        location: "UWM Student Union 381",
        description: "Lastly, join us for our Speed Dating (career-wise, not the actual kind).",
        category: "Career",
    },
    {
        id: "convention-readiness-workshop",
        title: "Convention Readiness Workshop in Chicago",
        start: "2025-10-11T09:30:00",
        end: "2025-10-11T18:30:00",
        location: "750 S Halsted St, Chicago, IL 60607",
        description: "Join us for a professional workshop at the UIC - Student Centers for a convention in Chicago. We will be going over how to prepare for the convention, what to expect, and how to make the most out of your experience by building your public speaking and networking skills.",
        category: "Career",
    },
    {
        id: "bakery",
        title: "SHPE Bake Sale",
        start: "2025-10-14T11:00:00",
        end: "2025-10-14T15:00:00",
        location: "UWM Union",
        description: "",
        category: "Social",
    },
    {
        id: "gbm-2",
        title: "Second General Body Meeting",
        start: "2025-10-15T17:00:00",
        end: "2025-10-15T18:30:00",
        location: "UWM Union 280",
        description: "Join us for our second general body meeting, where we will discuss upcoming events and initiatives for the chapter. Additionally, the Milwaukee professional chapter will be joining us to share insights and opportunities.",
        category: "Workshop",
    },
    {
        id: "swe-shpe-material",
        title: "Cast A Keychain",
        start: "2025-10-31T13:00:00",
        end: "2025-10-31T15:00:00",
        location: "EMS E 371",
        description: "SWE and Material Advantage Club will be showing the movie Coraline and having snacks in CEAS E 371. Please wear long pants and closed toed shoes.",
        category: "Social",
    },
    {
        id: "uwm-marquette-john-deere-event",
        title: "UWM & Marquette John Deere Event",
        start: "2025-11-12T17:00:00",
        end: "2025-11-12T19:30:00",
        location: "UWM Student Union Fireside Lounge",
        description: "Join us for an exciting event hosted by John Deere in collaboration with UWM and Marquette University. This event will provide insights into career opportunities, industry trends, and networking with professionals from John Deere.",
        category: "Career",
    },
    {
        id: "friendsgiving-potluck",
        title: "Friendsgiving Potluck",
        start: "2025-11-21T17:00:00",
        end: "2025-11-21T19:00:00",
        location: "UWM Student Union 191",
        description: "Join us for our Friendsgiving Potluck! Bring your favorite dish to share and enjoy a meal with your fellow members.",
        category: "Social",
    },
    {
        id: "study-night-for-finals",
        title: "Study Night For Finals",
        start: "2025-12-10T17:30:00",
        end: "2025-12-10T20:00:00",
        location: "UWM LECWC 203",
        description: "Join us for a study night to prepare for finals. We'll have a quiet space to study and resources available to help you succeed! Snacks and drinks will be provided.",
        category: "Workshop",
    },
    {
        id: "holiday-social",
        title: "Holiday Social",
        start: "2025-12-12T17:00:00",
        end: "2025-12-12T19:00:00",
        location: "UWM Student Union 191",
        description: "Join us for our Holiday Social! We'll have food, drinks, and fun activities to celebrate the season! Fun way to unwind before finals.",
        category: "Social",
    },
];
